const slug = 'cellular-renewal-calculator';
const description = 'Calculate the percentage of your body that has renewed since birth. Estimates based on the cell division rate of organs, bones, and tissues. The Paradox of Theseus made tangible.';
const title = 'Cellular Renewal Calculator: How Much is Left of the Original "You"?';
const howTo = [
    {
      name: 'Adjust your age',
      text: 'Slide the selector from 1 to 105 years. This is the most important variable for renewal calculations.',
    },
    {
      name: 'Observe the main percentage',
      text: 'The large number in the center shows what percentage of your current matter is "new" (renewed since birth).',
    },
    {
      name: 'Analyze the progress bars',
      text: 'Each bar represents a different tissue: skin/blood, bone, organs, and brain. Notice how the brain barely changes while skin constantly renews.',
    },
    {
      name: 'Reflect on your identity',
      text: 'If 99% of you is new matter, who are you really? Use this tool as a starting point for reflections on personal continuity and the Paradox of Theseus.',
    },
  ];
const faq = [
    {
      question: 'What exactly is "cellular renewal"?',
      answer: 'It is the natural process by which aged or damaged cells die (apoptosis) and are replaced by new cells generated by mitotic division. This cycle is essential for maintaining functional tissues and repairing damage.',
    },
    {
      question: 'Why does the brain renew so slowly?',
      answer: 'Neurons in the cerebral cortex are generated before birth and generally do not divide further. This provides neurological stability: your fundamental "wiring" remains constant. However, glial (support) cells do renew. Memory is stored in connections, not in atoms.',
    },
    {
      question: 'Is it true that every 7 years we are "new people"?',
      answer: 'It is a simplification. It is not accurate. Your blood renews in 4 months, your skin in a month, your skeleton in 10 years. Your brain remains largely unchanged. The number 7 years is historical (Aristotle mentioned it) but biologically it is an imprecise average.',
    },
    {
      question: 'If my body is 99% new, am I still the same person?',
      answer: 'Yes. Identity is a continuity of information, consciousness, and memory, not of atoms. You are like a river: the water changes constantly, but the river persists. The Paradox of Theseus suggests that identity resides in the pattern, not the matter.',
    },
    {
      question: 'Which tissues renew the fastest?',
      answer: 'Blood and skin lead the way. Your bone marrow produces 200 billion blood cells daily. You lose ~30,000 skin cells per minute. This is why they heal so well and age so visibly: they are young in terms of cellular age.',
    },
    {
      question: 'Does the eye lens really not renew?',
      answer: 'Correct. Lens cells are deposited during embryonic development and are kept for life. At 100 years old, the central cells of your lens could be the same as when you were in the womb. It is a biological time capsule.',
    },
  ];
import { bibliography } from '../bibliography';
import type { ToolLocaleContent } from '../../../types';

export const content: ToolLocaleContent = {
  slug,
  title,
  description,
  ui: {
    copied: 'Copied',
    noHistory: 'No history',
    load: 'Load',
    delete: 'Delete',
    biologicalTimeline: 'Biological Timeline',
    ageUnit: 'years of evolution',
    matterNewPercent: 'Your matter is new by',
    atomicRenewal: 'Atomic Renewal',
    skinAndBlood: 'Skin and Blood',
    boneRemodeling: 'Bone Remodeling',
    organicMatrix: 'Organic Matrix',
    perennialCells: 'Perennial Cells',
    disclaimerText: 'Caclulations are based on mean cellular life according to isotopic studies. While blood and skin renew in weeks, lens proteins and much of your cerebral cortex remain from embryonic development. Physically, you are a dynamic structure in constant flux.',
  },
  seo: [
    {
      type: 'title',
      text: 'How much of you is really "yours"? The science of cellular renewal',
      level: 2,
    },
    {
      type: 'paragraph',
      html: 'Your body is a river in constant motion. Every second, millions of cells die and are replaced by new ones. In seven years, practically every atom in your body will have been replaced. However, this statistic is profoundly misleading, because different parts of your organism renew at radically different rates.',
    },
    {
      type: 'paragraph',
      html: 'This paradox, known as the <strong>Ship of Theseus Paradox</strong>, poses an ancient question: if you replace all the parts of something, is it still the same? In your case, it is a literal question. The atoms that make up your body today are not the same ones that were there 10 years ago, but <em>you</em> are still you.',
    },
    {
      type: 'title',
      text: 'Cellular Turnover: A Map of Your Dynamic Body',
      level: 3,
    },
    {
      type: 'paragraph',
      html: 'The speed of renewal varies dramatically by tissue:',
    },
    {
      type: 'table',
      headers: ['Tissue', 'Cellular Average Life', 'Full Renewal', 'Description'],
      rows: [
        ['<strong>Blood</strong>', '120 days', '4 months', 'Red blood cells are the fastest. Your bone marrow produces 200 billion daily.'],
        ['<strong>Skin</strong>', '2-4 weeks', '1 month', 'Extremely fast renewal. You lose ~30,000 skin cells per minute.'],
        ['<strong>Bone</strong>', '10 years', 'One decade', 'The skeleton is more conservative. Still, after 10 years, you will have replaced practically your entire skeleton.'],
        ['<strong>Organs</strong>', '15 years', '1.5 decades', 'The liver renews in months. The heart, in years. A mosaic of rhythms.'],
        ['<strong>Brain</strong>', '80+ years (neurons)', 'Almost never', 'Your cortical neurons from birth. But glia (support cells) do renew.'],
      ],
    },
    {
      type: 'title',
      text: 'The Eye Lens: The Oldest Part of You',
      level: 3,
    },
    {
      type: 'paragraph',
      html: 'There is one structure in your body that is special: the <strong>eye lens</strong>. The cells that make up the lens are deposited during fetal development and are never replaced. If you live to be 100 years old, the central cells of your lens will still be the same ones you had in your mother\'s womb. They are, literally, the oldest part of you.',
    },
    {
      type: 'title',
      text: 'Total Renewal Calculation: The Paradox of Weights',
      level: 3,
    },
    {
      type: 'paragraph',
      html: 'This calculator uses a weighted average of different tissues:',
    },
    {
      type: 'list',
      items: [
        '<strong>30% skin and blood:</strong> Almost complete renewal in younger years.',
        '<strong>35% skeleton:</strong> Progressive renewal, reaching 100% at 10 years.',
        '<strong>25% organs:</strong> Slower renewal, variable by organ.',
        '<strong>10% brain:</strong> Minimal change in neurons, maximum in support structures.',
      ],
    },
    {
      type: 'paragraph',
      html: 'The result is that at age 25, approximately <strong>93% of your current matter is new</strong>. By age 80, you could be composed of more than 99% different atoms than those you had at birth.',
    },
    {
      type: 'title',
      text: 'Philosophical Implications: Identity is Information, Not Matter',
      level: 3,
    },
    {
      type: 'paragraph',
      html: 'If your body is completely new every decade, why is it "you"? The answer is that identity resides not in specific atoms, but in the <strong>pattern of information</strong> that those atoms hold. You are like a song: it\'s not the same air vibrating, but the pattern persists.',
    },
    {
      type: 'paragraph',
      html: 'This has profound implications: your body is a process, not a thing. You are a self-organizing pattern that persists through change. You don\'t own atoms; you are a structure that channels them temporarily.',
    },
  ],
  faq,
  bibliography,
  howTo,
  
  schemas: [
    {
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: title,
      description: description,
      applicationCategory: 'ScientificApplication',
      operatingSystem: 'Any',
    },
    {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: faq.map((item) => ({
        '@type': 'Question',
        name: item.question,
        acceptedAnswer: {
          '@type': 'Answer',
          text: item.answer,
        },
      })),
    },
    {
      '@context': 'https://schema.org',
      '@type': 'HowTo',
      name: title,
      step: howTo.map((step) => ({
        '@type': 'HowToStep',
        name: step.name,
        text: step.text,
      })),
    },
  ],
};

